(global-set-key (kbd "<escape>") 'keyboard-escape-quit)

;; Changes Show Hide Keys
(global-set-key (kbd "C-'") 'hs-hide-block)
(global-set-key (kbd "C-;") 'hs-show-block)
(global-set-key (kbd "C-\"") 'hs-hide-all)
(global-set-key (kbd "C-:") 'hs-show-all)
(global-set-key (kbd "<C-tab>") 'origami-toggle-node)

;;spell check correction
(global-set-key (kbd "C-c s") 'flyspell-correct-word-before-point)

;; Org-Agenda/Capture
(global-set-key (kbd "C-c a") 'org-agenda)
(global-set-key (kbd "C-c t") 'org-capture)

;; Insert greek chars
(global-set-key (kbd "C-M-g a") "α")
(global-set-key (kbd "C-M-g b") "β")
(global-set-key (kbd "C-M-g g") "γ")
(global-set-key (kbd "C-M-g d") "δ")
(global-set-key (kbd "C-M-g e") "ε")
(global-set-key (kbd "C-M-g z") "ζ")
(global-set-key (kbd "C-M-g h") "η")
(global-set-key (kbd "C-M-g q") "θ")
(global-set-key (kbd "C-M-g i") "ι")
(global-set-key (kbd "C-M-g k") "κ")
(global-set-key (kbd "C-M-g l") "λ")
(global-set-key (kbd "C-M-g m") "μ")
(global-set-key (kbd "C-M-g n") "ν")
(global-set-key (kbd "C-M-g x") "ξ")
(global-set-key (kbd "C-M-g o") "ο")
(global-set-key (kbd "C-M-g p") "π")
(global-set-key (kbd "C-M-g r") "ρ")
(global-set-key (kbd "C-M-g s") "σ")
(global-set-key (kbd "C-M-g t") "τ")
(global-set-key (kbd "C-M-g u") "υ")
(global-set-key (kbd "C-M-g f") "ϕ")
(global-set-key (kbd "C-M-g j") "φ")
(global-set-key (kbd "C-M-g c") "χ")
(global-set-key (kbd "C-M-g y") "ψ")
(global-set-key (kbd "C-M-g w") "ω")
(global-set-key (kbd "C-M-g A") "Α")
(global-set-key (kbd "C-M-g B") "Β")
(global-set-key (kbd "C-M-g G") "Γ")
(global-set-key (kbd "C-M-g D") "Δ")
(global-set-key (kbd "C-M-g E") "Ε")
(global-set-key (kbd "C-M-g Z") "Ζ")
(global-set-key (kbd "C-M-g H") "Η")
(global-set-key (kbd "C-M-g Q") "Θ")
(global-set-key (kbd "C-M-g I") "Ι")
(global-set-key (kbd "C-M-g K") "Κ")
(global-set-key (kbd "C-M-g L") "Λ")
(global-set-key (kbd "C-M-g M") "Μ")
(global-set-key (kbd "C-M-g N") "Ν")
(global-set-key (kbd "C-M-g X") "Ξ")
(global-set-key (kbd "C-M-g O") "Ο")
(global-set-key (kbd "C-M-g P") "Π")
(global-set-key (kbd "C-M-g R") "Ρ")
(global-set-key (kbd "C-M-g S") "Σ")
(global-set-key (kbd "C-M-g T") "Τ")
(global-set-key (kbd "C-M-g U") "Υ")
(global-set-key (kbd "C-M-g F") "Φ")
(global-set-key (kbd "C-M-g J") "Φ")
(global-set-key (kbd "C-M-g C") "Χ")
(global-set-key (kbd "C-M-g Y") "Ψ")
(global-set-key (kbd "C-M-g W") "Ω")
